### ISSUE TITLE
Test suite refactoring

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#317]
This is a living issue to keep track of any ideas around making our test suite better

- [x] Simplify the test data setup to use the new `makeTask` overloads and not set the `dueDate` via a signed transaction, e.g. in https://github.com/JoinColony/colonyNetwork/pull/315/files#diff-c973fa0b369a707dd3dcba1d13c542bfL60
- [x] @area pointed out the `colony-reputation-mining-failed-to-respond-in-time` error message shows when the submission in question has not yet failed to respond whereas the message definitely makes it sound like it has. Maybe `colony-reputation-mining-challenge-not-timed-out` is more appropriate?
- [x] Check there are no simple `assert()`s and everything is `assert.isTrue` 
- [x] For the mining tests, explore other ways to `giveUserCLNYTokensAndStake` rather than completing a task. Possibly if we create the token authority for the CLNY token and allow the coinbase account to call `mint`, we can achieve that. Currently it complicates our reputation mining tests as these task completions incur reputation changes.
Note that as part of #387 we are already introducing the CLNY Authority as defined in the colonyToken repo. 
- [x] In mining tests, when a bad client fails to complete a challenge, we should check the error returned is what we expect, e.g. in `respondToChallenge` function the bad client should get back an error it's failing at the point we are testing. Also outlined by @area [here](https://github.com/JoinColony/colonyNetwork/issues/201#issuecomment-408474449)
- [x] General refactoring of the entire main test suite to get rid of unnecessary setup and checks in tests and focus on _unit_ testing as some tests feel more like integration testing. e.g. Decide if we really need the `colony.js`, `metacolony.js`, `reputation-change.js` tests to redeploy an entire network at the start of every test.
- [x] Look for ways to speed up coverage testing, e.g. exclude tests that are not testing contract functionality such as the reputation mining client test set 
- [x] At the very least investigate and maybe complete the work for bringing test coverage up to as close to 100% as possible. Log any new issues for distinct pieces of logic that need covering if it proves too much for the scope of this work.
- [x] Add test coverage and checks for the reputation mining client (logged as https://github.com/JoinColony/colonyNetwork/issues/523)
- [x] In mining tests, work on restoring good state even after a test fails. Currently if a test fails in `colony-network-mining.js` test fails, the test run exits. (logged separately as https://github.com/JoinColony/colonyNetwork/issues/524)

**Comment by elenadimitrova** [comment]
Also switch all `solium` warnings to errors as per comment here:
https://github.com/JoinColony/colonyNetwork/pull/320#discussion_r212904948

**Comment by kronosapiens** [comment]
@elenadimitrova @area Regarding the issue of distributing CLNY without going through a task flow, are we comfortable with giving the founder the ability to mint and distribute tokens? Is it something we might want to include only in tests, but remove before actual deployment?

**Comment by elenadimitrova** [comment]
We can already call `mintTokens` the problem is bypassing the Colony funding mechanism and shifting the minted tokens directly to a user. If we allow that in general, and outside of our tests, it will open the door to Colony founders circumventing token rewards and network fees and paying their users directly. Arguably the opposing point is valid too, where managing the colony funds outside of the task  workflow is needed.

**Comment by kronosapiens** [comment]
Sure, that is more my point: currently, founders can mint tokens but not distribute them without input from reputation holders. Note that direct payments give no reputation, which intuitively should work in our favor (to lessen the impact of abuse). I'll leave it as a discussion question for now.

**Comment by elenadimitrova** [comment]
Also I though I removed `eslint` `no-await-in-loop` rule as we have tons of places where this is disabled on a per-line basis but apparently not. We should investigate if there's a way to solve that and if not, disable it entirely in the project.

**Comment by kronosapiens** [comment]
🎉 🎉 🎉 🎉 🎉 🎉
